# Server
server.port=8080

# Database
# Aquí cambiamos "password" por tu contraseña real "Franhicode"
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
# Usamos tu nueva clave secreta aquí
jwt.secret=
jwt.expiration=

# CORS
cors.allowed-origins=http://localhost:5173

# Logging
logging.level.com.dental=DEBUG
logging.level.org.springframework.security=DEBUG